language: node_js
node_js:
    - "10"
    - "12"
    - "14"

before_script:

script:
    - npm run lint
    - npm test

after_success:
   - npm install --no-save nyc codecov
   - npm run cover
   - npx codecov

sudo: false
